### ISSUE TITLE
argument 1 has unexpected type 'NoneType'

### ISSUE THREAD

**Issue by Mte90** [Mte90/pugdebug#4]
```
Traceback (most recent call last):
  File "/home/mte90/Desktop/Prog/pugdebug/pugdebug/pugdebug.py", line 932, in handle_breakpoints_listed
    document_widget = self.document_viewer.get_document_by_path(path)
  File "/home/mte90/Desktop/Prog/pugdebug/pugdebug/gui/documents.py", line 73, in get_document_by_path
    return self.widget(index)
TypeError: widget(self, int): argument 1 has unexpected type 'NoneType'
```

I got that error but I cannot replicate it.

**Comment by andreym333** [comment]
Please provide the output of the 'git status' command in the program directory.

**Comment by Mte90** [comment]
You are right my instance wasn't updated -.-'

**Comment by Mte90** [comment]
I got that also with the latest commit:
```
Traceback (most recent call last):
  File "/home/mte90/Desktop/Prog/pugdebug/pugdebug/pugdebug.py", line 754, in handle_breakpoints_listed
    document_widget = self.document_viewer.get_document_by_path(
  File "/home/mte90/Desktop/Prog/pugdebug/pugdebug/gui/documents.py", line 77, in get_document_by_path
    return self.widget(index)
TypeError: widget(self, int): argument 1 has unexpected type 'NoneType'
```
